apiVersion: v1
kind: Namespace  # https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
metadata:   #
  name: ckad-ns
  labels:     # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    env: dev
    app: tutoring
    type: ns
---
apiVersion: v1
kind: Pod
metadata:
  name: ckad-pod
  namespace: ckad-ns
  labels:     # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    env: dev
    app: tutoring
    type: po
spec:
  containers: # https://kubernetes.io/docs/concepts/containers/
  - name: myapp-nginx
    image: nginx  # http://hub.docker.com/_/nginx
    args:
    - sleep
    - "10000"
